Refactor to simplify the benchmarking interfaces…
neuralmagic/deepsparse pull request #12
Opened 2021-01-18 19:24 UTC by markurtz

… by assuming all data is batched. Additionally, add in a root helper for benchmark_model

2021-01-18 19:30 UTC, bfineran requested changes
looks good pending doc string fix

2021-01-18 19:31 UTC, mgoin submitted a review, later dismissed
thank you

2021-01-19 14:41 UTC, bfineran approved these changes

2021-01-19 14:48 UTC, mgoin approved these changes

2021-01-19 15:04 UTC, merged