Inference UX, accept input data
neuralmagic/deepsparse pull request #1285
Opened 2023-09-26 17:32 UTC by horheynm

From the inference cli, accept input data.

` deepsparse.infer zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none --data sample.(csv|txt|json|jsonl)`

2023-09-27 13:28 UTC, rahul-tuli requested changes

2023-09-27 13:28 UTC, rahul-tuli commented on src/deepsparse/transformers/inference/infer.py
> +        sampling_temperature=sampling_temperature,
```suggestion
        temperature=sampling_temperature,
```

2023-09-27 19:02 UTC, bfineran approved these changes

2023-10-02 14:50 UTC, bfineran approved these changes

2023-10-02 16:44 UTC, rahul-tuli submitted a review, later dismissed

2023-10-02 16:44 UTC, rahul-tuli commented on src/deepsparse/transformers/inference/prompt_parser.py
> +        raise UnableToParseExtentionException(
nit: Extension --> extension

2023-10-02 19:24 UTC, rahul-tuli approved these changes

2023-10-02 19:45 UTC, bfineran approved these changes

2023-10-02 19:47 UTC, merged