[Fix] deepsparse – tokenizer stride size issue with original transformers
neuralmagic/deepsparse pull request #1425
Opened 2023-11-21 16:23 UTC by dbogunowicz

Fix for: https://app.asana.com/0/1205724081986514/1205993362080974
(the exhaustive explanation for this fix is in the ticket)

2023-11-21 17:13 UTC, dbarbuzzi commented
The changes work with the minimal example reported. Quick question, though, is it expected that if the consumer uses a non-default sequence_length that they should also be manually defining the doc_stride? I ask because now if I e.g. set a sequence_length of 32 in the constructor with no other kwargs, it will fail the new check in the PR as the doc_stride simply defaults to `62` regardless.

2023-11-21 17:29 UTC, dbogunowicz commented
@dbarbuzzi I understand your concerns. Let me take a look at what are HF default settings.

2023-11-21 18:49 UTC, dbogunowicz commented
@dbarbuzzi 
https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/question_answering.py#L408
It's pretty explicit here.

2023-11-21 18:55 UTC, dbogunowicz commented
@dbarbuzzi let's set doc_stride to None by default and compute it dynamically to avoid the issue. I think this is fine.

2023-11-22 15:19 UTC, bfineran requested changes

2023-11-22 15:19 UTC, bfineran commented on src/deepsparse/transformers/pipelines/question_answering.py
> +        if doc_stride is None:
let's see if we can read the number of special tokens from the tokenizer or tokenizer config and cap doc stride at `min(doc_stride, sequence_len - num_special_tokens)`

2023-11-22 15:19 UTC, bfineran commented on src/deepsparse/transformers/pipelines/question_answering.py
> +        if doc_stride is None:
and then let's add short warning

2023-11-22 18:04 UTC, bfineran approved these changes

2023-11-22 18:04 UTC, merged