moving YOLOv3 examples to unified YOLO examples directory
neuralmagic/deepsparse pull request #147
Opened 2021-07-22 20:46 UTC by bfineran

* support a single location for YOLOv3 and YOLOv5 examples since most code can be shared between the two
* support for generic anchor grids will be added in a follow up PR
* YOLOv5 model stubs and examples to be added after v5 lands in SparseZoo

2021-07-23 16:13 UTC, jeanniefinks commented on examples/ultralytics-yolo/README.md
> +Each model in the SparseZoo has a specific stub that identifies it, any YOLO model stub in the SparseZoo can be used to
```suggestion
Each model in the SparseZoo has a specific stub that identifies it; any YOLO model stub in the SparseZoo can be used to
```

2021-07-23 16:14 UTC, jeanniefinks commented on examples/ultralytics-yolo/deepsparse_utils.py
> +Utilities for YOLO pre and post processing for DeepSparse pipelines
```suggestion
Utilities for YOLO pre- and post-processing for DeepSparse pipelines
```

2021-07-23 16:14 UTC, jeanniefinks commented on examples/ultralytics-yolo/deepsparse_utils.py
> +    Class for performing postprocessing of YOLO model predictions
```suggestion
    Class for performing post-processing of YOLO model predictions
```

2021-07-23 16:23 UTC, jeanniefinks requested changes
There were some other edits I noticed in README; decide if you want to keep them in scope here or file a separate PR, make it so.

- Search for the phrase: "or glog pat" - have no idea what that is?
- Update this line to be: Note for quantized performance, your CPU must support VNNI instructions. Review `/proc/cpuinfo` for the flag `avx512_vnni` to verify chipset compatibility.
- Under "Server" - we had enhanced the content per the "Server" section of this file:
https://github.com/neuralmagic/deepsparse/blob/main/examples/classification/README.md

2021-07-26 19:26 UTC, bfineran commented
@jeanniefinks added your suggestions into this PR

2021-07-26 19:51 UTC, finkatronic approved these changes
lgtm!

2021-07-26 19:56 UTC, jeanniefinks commented
> lgtm!

Ugh, was logged with other identity. Will try to fix this

2021-07-26 20:05 UTC, jeanniefinks approved these changes

2021-07-26 20:09 UTC, mgoin approved these changes

2021-07-26 23:12 UTC, markurtz approved these changes
Note that we'll need to keep an eye on the links for updating so we don't end up with dead ones for the model page and readmes

2021-07-27 14:18 UTC, bfineran commented
@markurtz noted, will go through the sparseml side of things

2021-07-27 14:18 UTC, merged