Add CLIP model to enable test_clip.py
neuralmagic/deepsparse pull request #1500
Opened 2023-12-27 15:24 UTC by mgoin

Since we've made a quantized CLIP (https://huggingface.co/neuralmagic/CLIP-ViT-B-32-256x256-DataComp-s34B-b86K-quant-ds), let's use it to test our pipeline!

2023-12-27 18:38 UTC, dsikka requested changes
Will this model work just for classification or for captioning as well? From the OpenCLIP models available, only a small fraction worked for captioning. 

Can we add a description of the available models somewhere? Either in a read me or docstring?

2023-12-27 19:55 UTC, mgoin commented
@dsikka it is just made for image/text retrieval and zero-shot image classification. I left in the pytest.skip for the captioning test as a result. 
This model was made from [OpenCLIP using a special branch](https://github.com/neuralmagic/open_clip/tree/jen/clip) that @ohaijen worked on. This was made as a collaboration so we're focused on getting results and pipelines working quickly - this is why we pushed to HF and everything to run the model is pretty much self-contained within that model card and notebooks.
My opportunistic thinking here was that we could use the model we're using on HF for some active testing on DeepSparse. I don't think there are plans on pushing CLIP models to SparseZoo at the moment, but if you think it's necessary for testing we could try to get a model up there.

2023-12-29 07:28 UTC, dbogunowicz approved these changes

2024-01-02 14:23 UTC, dsikka requested changes
A few small comments otherwise LGTM

2024-01-02 14:23 UTC, dsikka commented on tests/deepsparse/pipelines/test_clip.py
> +    from deepsparse.legacy import Pipeline
shouldnt be needed?

2024-01-02 14:23 UTC, dsikka commented on tests/deepsparse/pipelines/test_clip.py
> +    from deepsparse.legacy import Pipeline
same comment as above.

2024-01-02 14:23 UTC, dsikka commented on tests/deepsparse/pipelines/test_clip.py
> +    model_id = "neuralmagic/CLIP-ViT-B-32-256x256-DataComp-s34B-b86K-quant-ds"
Could we add a quick comment/note indicating that this model is not from OpenCLIP and only use for zero-shot classification?

2025-05-10 15:34 UTC, jeanniefinks commented
Per the main [README announcement](https://github.com/neuralmagic/deepsparse/blob/main/README.md), DeepSparse is being deprecated by June 2, 2025. Closing the PR as work has been suspended; thank you for the inputs and support!

2025-05-10 15:34 UTC, closed without merging