[Text Generation] Consolidate `TextGenerationPipeline` and `TextGenerationPipelineNoKVCache`
neuralmagic/deepsparse pull request #1510
Opened 2024-01-05 13:21 UTC by dbogunowicz

2024-01-05 18:13 UTC, bfineran submitted a review, later dismissed

2024-01-08 20:11 UTC, anmarques reviewed
There is a discrepancy in the interface between cached and non-cached models. For cached models it takes sequences, whereas for cached models it takes promt

2024-01-09 21:03 UTC, dsikka requested changes
Is there anyway for us to consolidate some of the repeat code here? We set-up the model twice. We can just do it once, decide if kv_cache is present, and then pass the correct paths

2024-01-17 16:45 UTC, dsikka commented on src/deepsparse/pipeline.py
> -            _LOGGER.warning(f"Could not create v2 '{task}' pipeline, trying legacy")
Where'd it go

2024-01-18 09:54 UTC, dbogunowicz commented on src/deepsparse/pipeline.py
> -            _LOGGER.warning(f"Could not create v2 '{task}' pipeline, trying legacy")
blimey

2024-01-19 18:13 UTC, dsikka approved these changes
This LGTM. 

Can we just do a quick audit that the properties that were available before still work?
Specifically: model_path, tokenizer, input/output_schemas?
Also, can we confirm this PR didn't cause any issues: https://github.com/neuralmagic/deepsparse/pull/1523

If the above are true, can merge.

2024-01-19 18:19 UTC, bfineran approved these changes

2024-01-22 10:01 UTC, dbogunowicz commented
@dsikka all units/integrations tests pass with #1523 included.
I confirm that all the aforementioned properties are still present and functional in both "incarnations" of TextGenerationPipeline

2024-01-22 10:10 UTC, merged