benchmark server pipeline
neuralmagic/deepsparse pull request #1600
Opened 2024-02-12 21:34 UTC by horheynm

server running pipeline for benchmark

Note: Cannot have continuous batching with timer middleware.

## Configs

### Server side
```bash
deepsparse.server --config_file config.yaml
```

```json
num_cores: 2
num_workers: 2
endpoints:
  - task: text_generation
    model: "hf:mgoin/TinyStories-1M-ds"
    # kwargs: {"continuous_batch_sizes": [2]}
    middlewares:
      - TimerMiddleware

```

### client side
```python3
import requests

url = "http://localhost:5543/v2/models/text_generation-0/benchmark"

obj = {
    "data_type": "dummy",
    "gen_sequence_length": 100,
    "pipeline_kwargs": {},
    "input_schema_kwargs": {}
} 

response = requests.post(url, json=obj)
print(response.json())

```

2024-02-26 18:27 UTC, dbogunowicz submitted a review, later dismissed
Can we have some tests in?

2024-02-26 20:20 UTC, dsikka requested changes
Great job!

- Lets test with an openai example to make sure the integration works
- Add testing, specifically around benchmark_pipeline and server integration
- Refactor benchmark_pipeline function to prevent repeat code

2024-02-26 20:20 UTC, dsikka commented on src/deepsparse/benchmark/benchmark_pipeline.py
> +def benchmark_from_pipeline(
refactor

2024-03-04 15:33 UTC, horheynm commented
> Great job!
> 
> * Lets test with an openai example to make sure the integration works
> * Add testing, specifically around benchmark_pipeline and server integration
> * Refactor benchmark_pipeline function to prevent repeat code

I addressed tests and refactor, but not testing with openai - talking to Ben, dont need it for now

2024-03-06 15:23 UTC, dsikka approved these changes

2024-03-06 18:39 UTC, dbogunowicz approved these changes

2024-03-06 18:41 UTC, merged