Fix the logic for perplexity evaluation (`Not enough kv_cache capacity to run generation. Please use a larger sequence_length or a shorter prompt`)
neuralmagic/deepsparse pull request #1633
Opened 2024-03-07 12:58 UTC by dbogunowicz

2024-03-11 14:40 UTC, bfineran requested changes
looks like this may be out of date or not ready to merge @dbogunowicz?

2024-03-11 14:40 UTC, bfineran commented on src/deepsparse/evaluation/integrations/perplexity.py
> +                print(len(pipeline.tokenizer(batch[0]).input_ids))
debug?

2024-03-11 14:40 UTC, bfineran commented on src/deepsparse/evaluation/integrations/perplexity.py
> +            breakpoint()
debug?

2024-04-22 11:29 UTC, dbogunowicz commented
Closing, due to inactivity.

2024-04-22 11:29 UTC, closed without merging