[Docs] Transformers DeepSparse Integration (also a template for the future similar, docs)
neuralmagic/deepsparse pull request #352
Opened 2022-05-06 07:31 UTC by dbogunowicz

2022-05-10 14:18 UTC, markurtz requested changes
Quick feedback on the DeepSparse template:

- let's include some mention of model sparsification (sparsity and quantization) and DeepSparse being specialized for these types of models
- in the getting started for ONNX Model Support let's rename this to something more generic such as Model Format. Underneath let's better organize everything we need in a local folder including the model.onnx, the tokenizer, etc. Can then call out that a SparseZoo stub can also be supplied and it will download all necessary files
- Also underneath this let's link out to export documentation in SparseML for the user to dive in further
- Let's remove the duplicate example of question answering for Python deployment. Instead, let's call out an API reference at the top and then give example code implementation for the different use cases
- Let's format the server in the same way as above for the Python deployment. Start with a CLI reference for the server and command args and then give examples for the different use cases

2022-05-25 09:12 UTC, dbogunowicz commented
@markurtz thank you for your comments, addressed most of them. That being said, could you clarify what you mean by:

```Let's remove the duplicate example of question answering for Python deployment. Instead, let's call out an API reference at the top and then give an example code implementation for the different use cases```

I am confused about what you mean by the API reference here. API reference for the `transformer.pipeline`? Is there a nice "user-facing" API reference for that?

2022-05-31 10:03 UTC, dbogunowicz commented on src/deepsparse/transformers/README.md
> +from deepsparse.transformers import pipeline
Interesting. Is this the intended behavior now? I don't see it working with the current `main`:

```
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepsparse import pipeline
>>> pipeline
<module 'deepsparse.pipeline' from '/home/damian/deepsparse_copy/src/deepsparse/pipeline.py'>
>>> from deepsparse.transformers import pipeline
>>> pipeline
<function pipeline at 0x7f2d0b3ead30>
```

Let's discuss this internally.

2022-06-01 16:03 UTC, markurtz commented on src/deepsparse/transformers/README.md
> +#### Text Classification Pipeline
Let's call out sentiment analysis as a separate pipeline and use a text classification example for mnli or qqp

2022-06-01 20:56 UTC, bfineran commented on src/deepsparse/transformers/README.md
> +The SparseML installation provides a CLI for sparsifying your models for a specific task; appending the `--help` argument displays a full list of options for training in SparseML:
fixing - will add in links after final filenames are set in sparseml

2022-06-01 21:12 UTC, bfineran commented
@markurtz refactored server section to point to the server docs

2022-06-01 22:51 UTC, jeanniefinks commented on src/deepsparse/transformers/README.md
> +DeepSparse allows accelerated inference, serving, and benchmarking of sparsified [HuggingFace transformer](https://github.com/huggingface/transformers) models.
```suggestion
DeepSparse allows accelerated inference, serving, and benchmarking of sparsified [Hugging Face Transformer](https://github.com/huggingface/transformers) models.  
```

2022-06-01 22:51 UTC, jeanniefinks commented on src/deepsparse/transformers/README.md
> +reduce compute required as well as accelerate memory-bound workloads. The Engine is particularly effective when leveraging sparsification
```suggestion
reduce compute required as well as accelerate memory-bound workloads. The engine is particularly effective when leveraging sparsification
```

2022-06-01 22:52 UTC, jeanniefinks commented on src/deepsparse/transformers/README.md
> +This grants the Engine the flexibility to serve any model in a framework-agnostic environment.
```suggestion
This grants the engine the flexibility to serve any model in a framework-agnostic environment. 
```

2022-06-01 22:53 UTC, jeanniefinks commented on src/deepsparse/transformers/README.md
> +#### Exporting the onnx file from the contents of a local directory
```suggestion
#### Exporting the ONNX file from the contents of a local directory
```

2022-06-01 22:53 UTC, jeanniefinks commented on src/deepsparse/transformers/README.md
> +Onnx models can be exported using the `sparseml.transformers.export_onnx` tool:
```suggestion
ONNX models can be exported using the `sparseml.transformers.export_onnx` tool:
```

2022-06-01 22:54 UTC, jeanniefinks commented on src/deepsparse/transformers/README.md
> +Alternatively, you can skip the process of onnx model export by downloading all the required model data directly from Neural Magic's [SparseZoo](https://sparsezoo.neuralmagic.com/).
```suggestion
Alternatively, you can skip the process of ONNX model export by downloading all the required model data directly from Neural Magic's [SparseZoo](https://sparsezoo.neuralmagic.com/).
```

2022-06-01 22:57 UTC, jeanniefinks commented on src/deepsparse/transformers/README.md
> +For a full example of deploying sparse transformer models with the DeepSparse server, see the
```suggestion
For a full example of deploying sparse transformer models with the DeepSparse Server, see the
```

2022-06-01 22:58 UTC, jeanniefinks commented on src/deepsparse/transformers/README.md
> +As an alternative to Python API, the DeepSparse inference server allows you to serve ONNX models and pipelines in HTTP.
```suggestion
As an alternative to Python API, the DeepSparse Server allows you to serve ONNX models and pipelines in HTTP.
```

2022-06-01 23:01 UTC, jeanniefinks requested changes
Few minor edits

2022-06-07 13:29 UTC, KSGulin commented on src/deepsparse/transformers/README.md
> +select a pruend and quantized model for the task from the `SparseZoo` that can be used for accelerated
```suggestion
select a pruned and quantized model for the task from the `SparseZoo` that can be used for accelerated
```

2022-06-07 17:07 UTC, markurtz approved these changes

2022-06-07 18:52 UTC, merged