Qa pipeline num spans
neuralmagic/deepsparse pull request #399
Opened 2022-05-31 20:25 UTC by kylesayrs

This PR adds support for a max_num_spans argument to the QA pipeline. When the given context is too long, the inputs will be split across multiple spans. This argument limits the maximum number of spans that will be fed to the model.

2022-06-02 20:40 UTC, rahul-tuli approved these changes, later dismissed

2022-06-02 20:54 UTC, bfineran requested changes
Looks great @kylesayrs pending name change. Let's run this through `deepsparse.transformers.eval_downstream` for a QA task and model to make sure nothing broke with this

2022-06-02 20:54 UTC, bfineran commented on src/deepsparse/transformers/pipelines/question_answering.py
> +    :param max_num_spans: if the context is too long to fit with the question for the
let's rename to just `num_spans` to be consistent with the transformers repo

2022-06-02 21:50 UTC, kylesayrs commented
python3 eval_downstream.py zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/base-none --dataset squad --max-samples 150

{'exact_match': 85.52631578947368, 'f1': 90.95891903672225}

2022-06-07 19:14 UTC, bfineran approved these changes

2022-06-07 19:15 UTC, rahul-tuli approved these changes
GG Kyle!
<img src="https://media2.giphy.com/media/jmS6YojdAaYw5z1LHi/giphy.gif"/>

2022-06-08 03:52 UTC, merged