Added pipeline creation functions
neuralmagic/deepsparse pull request #402
Opened 2022-06-01 16:24 UTC by kylesayrs

This PR adds creation functions that allow easier pipeline creation. The new functions positional arguments and keyword arguments to be passed.

2022-06-02 20:47 UTC, rahul-tuli commented on src/deepsparse/pipeline.py
> +    return Pipeline.create(*(("question_answering",) + args), **kwargs)
This is so cool

2022-06-02 20:47 UTC, rahul-tuli submitted a review, later dismissed

2022-06-02 20:52 UTC, bfineran requested changes
looks good overall @kylesayrs.

it's nice that using generic args, keyword args for these will limit the impact downstream updates causing future issues if these functions aren't updated, let's at least get the existing docstrings for each of these pipelines copied in though, so when docs are generated, each of these functions will have some info on what should be included

2022-06-02 20:52 UTC, bfineran commented on src/deepsparse/pipeline.py
> +def text_classification_pipeline(*args, **kwargs) -> "Pipeline":
let's make another one called `sentiment_analysis_pipeline` that does the same thing

2022-06-02 20:52 UTC, bfineran commented on src/deepsparse/pipeline.py
> +    return Pipeline.create(*(("question_answering",) + args), **kwargs)
any reason we can't do `Pipeline.create("question-answering", *args, **kwargs)` a little easier to read

2022-06-07 16:40 UTC, bfineran approved these changes

2022-06-07 16:47 UTC, rahul-tuli approved these changes

2022-06-07 19:13 UTC, merged