Batch splitting
neuralmagic/deepsparse pull request #50
Opened 2021-02-23 19:02 UTC by bnellnm

This adds support for batch-splitting in the engine, i.e. if the number of the sockets on the system is > 1, then the model is split into batch_size/num_sockets smaller models which each run on their own socket.

Batch splitting will be enabled whenever num_sockets >1 unless explicitly disabled by setting use_batch_splitting to False.

2021-02-23 22:58 UTC, mgoin submitted a review, later dismissed
LGTM, thanks Bill

2021-02-25 17:43 UTC, markurtz requested changes
Need to run make style to format it, other than that looks good

2021-02-25 22:27 UTC, markurtz approved these changes

2021-02-25 22:28 UTC, mgoin approved these changes

2021-02-25 23:13 UTC, merged