Sparsezoo v2 updates
neuralmagic/deepsparse pull request #524
Opened 2022-07-28 18:12 UTC by rahul-tuli

2022-07-29 23:03 UTC, bfineran requested changes
first review - will make suggested changes

2022-07-29 23:03 UTC, bfineran commented on src/deepsparse/transformers/helpers.py
> +        raise_value_error = True
why is this logic change needed? taking a look

2022-07-29 23:09 UTC, bfineran commented
noting `test_engine`, `test_multi_engine`,  `test_examples`, and `test_custom_pipeline` will also need to be updated

2022-07-29 23:21 UTC, bfineran commented
Pipelines from stubs passing manual local testing as well as `eval_downstream` with
```bash
deepsparse.transformers.eval_downstream zoo:nlp/sentiment_analysis/obert-base/pytorch/huggingface/sst2/pruned90-none --dataset sst2 --max-sequence-length 128
```

2022-07-30 00:16 UTC, bfineran commented
verified stub input to `Engine` passes locally

2022-07-30 00:37 UTC, bfineran commented
tests and src passing outside of `examples` and those tests now, opening for review.

will discuss early monday plans for examples

2022-08-01 16:37 UTC, dbogunowicz submitted a review, later dismissed

2022-08-01 16:52 UTC, bfineran approved these changes

2022-08-01 16:52 UTC, dbogunowicz approved these changes

2022-08-01 18:24 UTC, merged