Removing predictions from YOLOOutput
neuralmagic/deepsparse pull request #637
Opened 2022-09-08 19:22 UTC by corey-nm

This field just contains what all the other fields in the output contains, so its very redundant. 

Unit tested and searched codebase for any use of "predictions"

2022-09-08 20:21 UTC, bfineran requested changes
looks like this doc needs update: https://github.com/neuralmagic/deepsparse/blob/87b2b5d900ac8de1ad348be72fc30f739b06c545/src/deepsparse/yolo/README.md?plain=1#L137

2022-09-08 20:23 UTC, corey-nm commented
> looks like this doc needs update:
> 
> https://github.com/neuralmagic/deepsparse/blob/87b2b5d900ac8de1ad348be72fc30f739b06c545/src/deepsparse/yolo/README.md?plain=1#L137

Fixed, great catch. That should've been using boxes anyway!

2022-09-08 20:45 UTC, bfineran approved these changes

2022-09-09 12:07 UTC, KSGulin approved these changes

2022-09-09 13:15 UTC, merged