Adding GKE to examples
neuralmagic/deepsparse pull request #646
Opened 2022-09-12 15:33 UTC by corey-nm

Adds link to GKE tutorial on how to deploy a dockerized web server to GKE. I don't think we should duplicate this information in our repo's readme because:
1. The GKE tutorial has a TON of useful commands/help.
2. It makes it explicit that we don't require anything special to run on GKE. This means users with GKE experience already don't need to read through our README just to find out that we are using normal GKE commands.
3. Any docs duplicated here may become out of date.

test plan: built and ran docker image locally

2022-09-12 19:33 UTC, bfineran commented on examples/google-kubernetes-engine/server-config.yaml
> +num_workers: 1
should remove this as we will use the defaults once added

2022-09-12 19:37 UTC, bfineran requested changes
let's add support to the dockerfile to support any server config that comes in. also need to document/support how to mount custom deployment directories to the image that the configs can reference

also should at minimum add a section to the readme demonstrating how to make an inference request to GKE once everything is spun up, even if the rest is through their tutorial

2022-09-13 13:51 UTC, corey-nm commented
> let's add support to the dockerfile to support any server config that comes in. also need to document/support how to mount custom deployment directories to the image that the configs can reference
> 
> also should at minimum add a section to the readme demonstrating how to make an inference request to GKE once everything is spun up, even if the rest is through their tutorial

What do you mean by custom deployment directories? I imagine that could be covered in a separate example just going over that with docker.

I added a section to readme, you can interact with it just like any other web server so pretty straightforward!

2022-09-13 14:01 UTC, bfineran requested changes
So right now, to use the Dockerfile, users need to edit `server-config.yaml`, or copy the Dockerfile into the directory where their own `server-config.yaml` exists.  Am suggesting that we add support for a config arg along with documentation for it.

Also includes needing to add documentation for how to mount models to the image that the server config can read from local deployment directories. (ie if a user obtains a local deployment directory from sparsify, writes a config for it, then wants to use the dockerfile to deploy to GKE)

2022-09-13 14:10 UTC, corey-nm commented on examples/README.md
> +| [Google Kubernetes Engine]() | How to deploy a DeepSparse inference server on GKE |
It'll work when it's merged into main

2022-09-13 14:41 UTC, rahul-tuli approved these changes

2022-09-13 14:41 UTC, rahul-tuli commented on examples/google-kubernetes-engine/Dockerfile
> +RUN git clone https://github.com/neuralmagic/deepsparse.git --depth 1 -b $GIT_BRANCH
nice!

2022-09-13 15:14 UTC, bfineran commented on examples/README.md
> +| [Google Kubernetes Engine]() | How to deploy a DeepSparse inference server on GKE |
issue isn't branch. it looks like the link for SM is pointing to GKE and the GKE link is missing

2022-09-13 15:15 UTC, corey-nm commented on examples/README.md
> +| [Google Kubernetes Engine]() | How to deploy a DeepSparse inference server on GKE |
Oooooh woops thank you

2022-09-13 15:16 UTC, corey-nm commented on examples/README.md
> +| [Google Kubernetes Engine]() | How to deploy a DeepSparse inference server on GKE |
Fixed

2022-09-14 20:36 UTC, bfineran approved these changes

2022-09-15 11:56 UTC, KSGulin approved these changes

2022-09-15 13:41 UTC, merged