[Data Logging] "ServerConfig" to Logger
neuralmagic/deepsparse pull request #720
Opened 2022-10-26 09:50 UTC by dbogunowicz

2022-10-26 15:29 UTC, corey-nm commented on src/deepsparse/server/build_logger.py
> +        subprocess_logger = SubprocessLogger(logger=function_logger)
@bfineran @dbogunowicz i think splitting out filtering behavior from function logger will make parsing logic much simpler (see code snippet above). without splitting there'd have to be some weird combination of multi logger with existing function logger (i'm struggling to even sketch it out). additionally, splitting into MatchLogger allows us to easily set different target loggers for different functions

2022-10-27 14:34 UTC, bfineran commented on src/deepsparse/server/config.py
> +    loggers: List[Union[Dict[str, Dict[str, Union[str, int]]], str]] = Field(
let's hold off on this for now

2022-10-28 09:48 UTC, dbogunowicz commented on src/deepsparse/server/config.py
> +    )
Will add default frequency in the other PR.

2022-10-28 10:58 UTC, dbogunowicz commented on tests/server/test_build_logger.py
> +    assert True
For now, I am testing it by pickling the class objects and comparing their pickled definitions. Once this PR gets approved, I will write a more appropriate code for comparison between `logger` and `expected logger`

2022-10-28 11:10 UTC, dbogunowicz commented on src/deepsparse/server/build_logger.py
> +        name = endpoint.name or endpoint.task
We should be checking for two possible unwanted scenarios:
- having the same endpoint name (self.task or self.name) for multiple endpoints
- having the same metric function being applied to the same target

This is a mental note for myself to check against those scenarios in the next PR (integrating `build_logger` into the Server).

2022-11-02 15:49 UTC, corey-nm requested changes
great start! super close IMO

2022-11-02 15:49 UTC, corey-nm commented on src/deepsparse/server/build_logger.py
> +def build_logger(server_config: ServerConfig) -> logger_objects.BaseLogger:
I think this looks good so far, we'll probably need to construct a different logger per endpoint, which is different than the original design layed out. that'll just involve breaking apart this function you have here, so pretty easy

2022-11-02 15:49 UTC, corey-nm commented on src/deepsparse/server/build_logger.py
> +    leaf_loggers = _build_leaf_loggers(loggers_config)
recommend handling this in the function that calls build_logger

2022-11-02 15:49 UTC, corey-nm commented on src/deepsparse/server/build_logger.py
> +    return logger
old code i assume?

2022-11-02 15:49 UTC, corey-nm commented on src/deepsparse/server/config.py
> +    loggers: Optional[List[Union[str, Dict[str, Dict[str, Any]]]]] = Field(
```suggestion
    loggers: Optional[Dict[str, Dict[str, Any]]] = Field(
```
what about this?

2022-11-04 16:45 UTC, closed without merging