Update NOTICE
neuralmagic/deepsparse pull request #744
Opened 2022-11-02 21:22 UTC by rgreenberg1

If this were downloaded to either community edition or enterprise edition through PyPI, it'd still be correct in both cases and should have us covered. 

To be revisited in the future, to update licenses and such down the line. This is a shorter term fix.

We will get Judson to review from the legal side.

2022-11-02 22:22 UTC, jeanniefinks approved these changes

2022-11-02 23:22 UTC, jeanniefinks commented on NOTICE
> +* For a copy of the Neural Magic Engine License (which governs the DeepSparse Community Edition only), please see LICENSE-NEURALMAGIC as included in the top-level directory of the deepsparse GitHub r
```suggestion
The Community Edition of the project's binary containing the DeepSparse Engine is licensed under the Neural Magic Engine License (https://github.com/neuralmagic/deepsparse/blob/main/LICENSE-NEURALMAGIC). Example files and scripts included in the deepsparse GitHub repository are licensed under the Apache License Version 2.0 (https://github.com/neuralmagic/deepsparse/blob/main/LICENSE) as noted.

The Enterprise Edition of the DeepSparse Engine (https://docs.neuralmagic.com/products/deepsparse-ent) requires a Trial License or can be fully licensed (https://neuralmagic.com/legal/master-software-license-and-service-agreement/) for production, commercial applications.
```

2022-11-02 23:23 UTC, jeanniefinks commented on NOTICE
> +* For a copy of the Neural Magic Engine License (which governs the DeepSparse Community Edition only), please see LICENSE-NEURALMAGIC as included in the top-level directory of the deepsparse GitHub r
I think this makes it clearer and covers both cases, no matter where you are looking at the Notice on GitHub, or downloaded in local env.

2022-11-02 23:24 UTC, jeanniefinks requested changes
See suggestion @rgreenberg1

2022-11-02 23:28 UTC, jeanniefinks commented on NOTICE
> +* For a copy of the Neural Magic Engine License (which governs the DeepSparse Community Edition only), please see LICENSE-NEURALMAGIC as included in the top-level directory of the deepsparse GitHub r
@rgreenberg1 you should confirm the final version of this gets copied to the package as well.

2022-11-03 01:18 UTC, jeanniefinks approved these changes

2022-11-04 19:29 UTC, mgoin approved these changes

2022-11-09 17:54 UTC, merged