Update LICENSE-NEURALMAGIC
neuralmagic/deepsparse pull request #771
Opened 2022-11-16 13:09 UTC by rgreenberg1

Updated with name change, updated date

2022-11-16 15:58 UTC, jeanniefinks commented on LICENSE-NEURALMAGIC
> +                  NEURAL MAGIC DEEPSPARSE COMMUNITY LICENSE AGREEMENT
```suggestion
Updated: November 16, 2022

NEURAL MAGIC DEEPSPARSE COMMUNITY LICENSE AGREEMENT
```

2022-11-16 15:58 UTC, jeanniefinks commented on LICENSE-NEURALMAGIC
> +Updated November 16, 2022
```suggestion
```

2022-11-17 18:51 UTC, jeanniefinks commented on LICENSE-NEURALMAGIC
>  with offices at 55 Davis Square STE 3, Somerville, MA 02144, and is licensed and not
```suggestion
with offices at 55 Davis Square STE 3, Somerville, MA 02144 United States, and is licensed and not 
```

2022-11-17 18:54 UTC, jeanniefinks commented on LICENSE-NEURALMAGIC
>  executable (object) code, and (b) any existing user guide and release notes. The
```suggestion
executable (object) code, (b) DeepSparse-branded components, and (c) any existing user guide and release notes. The 
```

2022-11-17 18:56 UTC, jeanniefinks requested changes
Assuming we can generically refer to Server, Pipeline, and Benchmark as "DeepSparse-branded" components if they are considered part of the Software. It's left intentionally generic to serve as umbrella to future components as well as potential name changes.

2022-11-17 19:03 UTC, jeanniefinks requested changes
@rgreenberg1 also update 
"or any purpose." to
"for any purpose."

2022-11-17 20:26 UTC, jeanniefinks submitted a review, later dismissed

2022-11-17 20:49 UTC, bnellnm submitted a review, later dismissed

2022-11-17 21:03 UTC, jeanniefinks approved these changes

2022-11-17 21:10 UTC, bnellnm approved these changes

2022-11-17 21:19 UTC, merged