Update NOTICE
neuralmagic/deepsparse pull request #772
Opened 2022-11-16 13:13 UTC by rgreenberg1

Name changes, removed DS Engine.

2022-11-16 15:36 UTC, jeanniefinks commented on NOTICE
> +DeepSparse Community is licensed under the Neural Magic DeepSparse License (https://github.com/neuralmagic/deepsparse/blob/main/LICENSE-NEURALMAGIC). Example files and scripts included in the deepspa
```suggestion
DeepSparse Community is licensed under the Neural Magic DeepSparse License (https://github.com/neuralmagic/deepsparse/blob/main/LICENSE-NEURALMAGIC). Some source code, example files and scripts included in the deepsparse GitHub repository or directory are licensed under the Apache License Version 2.0 (https://github.com/neuralmagic/deepsparse/blob/main/LICENSE) as noted.
```

2022-11-16 15:39 UTC, jeanniefinks requested changes
See minor edits so we're consistent in other places using the same language and it can be used across Docs, GH, and PyPI.

2022-11-17 18:47 UTC, jeanniefinks commented on README.md
> +  <h3> An inference runtime offering GPU-class performance on CPUs and APIs to integrate ML into your application. </h3>
```suggestion
  <h3> An inference runtime offering GPU-class performance on CPUs and APIs to integrate ML into your application.</h3>
```

2022-11-17 18:47 UTC, jeanniefinks commented on README.md
> +  <h3> An inference runtime offering GPU-class performance on CPUs and APIs to integrate ML into your application. </h3>
taglines/subheadlines  don't normally get periods at the end as we haven't been doing that stylistically throughout the site.

2022-11-17 18:48 UTC, jeanniefinks requested changes
tiny edit!

2022-11-17 20:47 UTC, rgreenberg1 commented
Updating the Notice file in DeepSparse and README.

2022-11-17 20:57 UTC, jeanniefinks commented on README.md
> +The Community Edition of the project's binary containing DeepSparse is licensed under the [Neural Magic DeepSparse Community License.](https://github.com/neuralmagic/deepsparse/blob/main/LICENSE-NEUR
```suggestion
[DeepSparse Community](https://docs.neuralmagic.com/products/deepsparse) is licensed under the [Neural Magic DeepSparse Community License.](https://github.com/neuralmagic/deepsparse/blob/main/LICENSE-NEURALMAGIC)
```

2022-11-17 20:59 UTC, rgreenberg1 commented on README.md
> +The Community Edition of the project's binary containing DeepSparse is licensed under the [Neural Magic DeepSparse Community License.](https://github.com/neuralmagic/deepsparse/blob/main/LICENSE-NEUR
This is the right one, yes?

2022-11-17 21:07 UTC, jeanniefinks approved these changes

2022-11-17 21:09 UTC, bnellnm approved these changes

2022-11-17 21:18 UTC, merged