[System Logging] Log request details
neuralmagic/deepsparse pull request #831
Opened 2022-12-21 14:04 UTC by dbogunowicz

2022-12-27 22:04 UTC, bfineran requested changes
great work on this one @dbogunowicz, LGTM pending comments

2022-12-27 22:04 UTC, bfineran commented on src/deepsparse/server/system_logging.py
> +REQUEST_DETAILS_IDENTIFIER_PREFIX = "request_details"
should move this to top level helper file so pipelines can also reference this constant.

2022-12-27 22:04 UTC, bfineran commented on src/deepsparse/server/system_logging.py
> +class SystemLoggingMiddleware(BaseHTTPMiddleware):
nice - let's sync offline on the lifecycle of system logs with this included

2022-12-27 22:04 UTC, bfineran commented on src/deepsparse/server/system_logging.py
> +    **kwargs: Any,
nit: rename to `**items` or something else more specific to indicate that these are actually the items to log

2022-12-27 22:04 UTC, bfineran commented on src/deepsparse/server/system_logging.py
> +    :param server_logger: the logger to log the metrics to
docstring missing prefix and kwargs

2022-12-27 22:04 UTC, bfineran commented on src/deepsparse/server/system_logging.py
> +            identifier="/".join([prefix, identifier]),
nit: `f"{prefix}/{identifier}"`

2022-12-29 15:20 UTC, dbogunowicz commented on src/deepsparse/server/system_logging.py
> +            log_request_details(self.server_logger, successful_request=0)
not to lose the error message

2022-12-29 15:21 UTC, dbogunowicz commented on src/deepsparse/server/system_logging.py
> +            self.server_logger, successful_request=int((response.status_code == 200))
actually 2.X.X

2022-12-29 15:22 UTC, dbogunowicz commented on src/deepsparse/server/system_logging.py
> +            log_request_details(self.server_logger, successful_request=0)
unittests

2022-12-29 15:23 UTC, dbogunowicz commented on src/deepsparse/server/system_logging.py
> +            log_request_details(self.server_logger, successful_request=0)
and log it

2022-12-30 18:10 UTC, bfineran approved these changes

2022-12-30 20:07 UTC, merged