[MLOps 1.5] [PrometheusLogger] Account for the presence of `BatchList` implementation
neuralmagic/deepsparse pull request #885
Opened 2023-01-25 11:54 UTC by dbogunowicz

2023-01-25 21:47 UTC, bfineran requested changes

2023-01-25 21:47 UTC, bfineran commented on src/deepsparse/loggers/helpers.py
> +        - if `value` is a dictionary:
might want to rebrand this function in general to `unwrap_logged_value` since we also do special list logic.

2023-01-25 21:47 UTC, bfineran commented on src/deepsparse/loggers/helpers.py
> +            if isinstance(child_value, list):
do we always generically want to unwrap lists? Should only be if it's a `BatchResult`, no?

2023-01-26 14:38 UTC, corey-nm approved these changes
👍

2023-01-26 14:44 UTC, bfineran approved these changes

2023-01-26 14:47 UTC, merged